addSbtPlugin("com.github.sbt" % "sbt-boilerplate" % "0.7.0")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "1.1.4")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.4.7")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.0")
addSbtPlugin("com.eed3si9n.jarjarabrams" % "sbt-jarjar-abrams" % "1.14.0")
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.10.1")
